# Test: Register a new user
POST http://localhost:3000/users/create
Content-Type: application/json

{
  "username": "test12",
  "password": "test12",
  "email": "test12@example.com"
}



###                                                                                                                                                                                                                                                               

# Test: Login with the new user credentials
POST http://localhost:3000/auth/login  
Content-Type: application/json

{
  "username": "test12",
  "password": "test12"
}

###
# Test: Invalid Login (Wrong Password)
POST http://localhost:3000/auth/login  
Content-Type: application/json

{
  "username": "john doe",
  "password": "wrongpassword"
}

###
# Test: Login with non-existent user
POST http://localhost:3000/auth/login  
Content-Type: application/json

{
  "username": "nonexistentuser",
  "password": "somepassword"
}
