POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMiIsImlhdCI6MTczNzkxMzExOCwiZXhwIjoxNzM3OTE2NzE4fQ.3zMTQGd9FDXIOUXWmzFjZvv0rKE5ANIexSuCBEBaD8c

{
  "title": "My First Post",
  "content": "This is the content of my first post."
}
